# Generated by Django 3.1.6 on 2021-04-14 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rate', models.IntegerField()),
                ('Comment', models.CharField(default='NONE', max_length=450)),
                ('DateTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoanhNghiep',
            fields=[
                ('MaDoanhNghiep', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('TenDoanhNghiep', models.CharField(max_length=60)),
                ('SoDienThoai', models.CharField(default='NONE', max_length=60)),
                ('Email', models.CharField(default='NONE', max_length=60)),
                ('MoTaDoanhNghiep', models.CharField(default='NONE', max_length=60)),
                ('CoCauDoanhNghiep', models.CharField(default='NONE', max_length=60)),
                ('QuyMoDoanhNghiep', models.CharField(default='NONE', max_length=60)),
                ('NganhNgheKinhDoanh', models.CharField(default='NONE', max_length=60)),
                ('DiaChiTruSoChinh', models.CharField(default='NONE', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DoanhNghiepCurrent',
            fields=[
                ('MaDoanhNghiep', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('TenDoanhNghiep', models.CharField(max_length=60)),
                ('SoDienThoai', models.CharField(default='NONE', max_length=60)),
                ('Email', models.CharField(default='NONE', max_length=60)),
                ('MoTaDoanhNghiep', models.CharField(default='NONE', max_length=60)),
                ('CoCauDoanhNghiep', models.CharField(default='NONE', max_length=60)),
                ('QuyMoDoanhNghiep', models.CharField(default='NONE', max_length=60)),
                ('NganhNgheKinhDoanh', models.CharField(default='NONE', max_length=60)),
                ('DiaChiTruSoChinh', models.CharField(default='NONE', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='DoiTac',
            fields=[
                ('MaDoiTac', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('TenDoiTac', models.CharField(max_length=60)),
            ],
            options={
                'get_latest_by': ['MaDoiTac'],
            },
        ),
        migrations.CreateModel(
            name='DonVanChuyen',
            fields=[
                ('MaDonVanChuyen', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('MaDonHang', models.CharField(max_length=60)),
                ('MaDoiTac', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoanAdmin',
            fields=[
                ('MaTaiKhoan', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('TenTaiKhoan', models.CharField(max_length=60)),
                ('MatKhau', models.CharField(max_length=60)),
                ('KieuTaiKhoan', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ThongTinVanChuyen',
            fields=[
                ('MaThongTinVanChuyen', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('MaDonHang', models.CharField(max_length=120)),
                ('ThoiGian', models.CharField(default='NONE', max_length=150)),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('TrangThai', models.CharField(default='NONE', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TuNhan',
            fields=[
                ('MaTuhan', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('HoVaTen', models.CharField(max_length=60)),
                ('SoDienThoai', models.CharField(default='NONE', max_length=60)),
                ('Email', models.CharField(default='NONE', max_length=60)),
                ('QueQuan', models.CharField(default='NONE', max_length=120)),
                ('DiaChiThuongTru', models.CharField(default='NONE', max_length=120)),
                ('CMND', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('BienSoXe', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('TinhTrangXe', models.CharField(default='NONE', max_length=60)),
                ('MaChuSoHuu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebsiteKLTN.doitac')),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoanDoiTac',
            fields=[
                ('MaTaiKhoan', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('TenTaiKhoan', models.CharField(max_length=60)),
                ('MatKhau', models.CharField(max_length=60)),
                ('KieuTaiKhoan', models.CharField(max_length=2)),
                ('MaDoiTac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebsiteKLTN.doitac')),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoanDoanhNghiep',
            fields=[
                ('MaTaiKhoan', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('TenTaiKhoan', models.CharField(max_length=60)),
                ('MatKhau', models.CharField(max_length=60)),
                ('KieuTaiKhoan', models.CharField(max_length=2)),
                ('MaDoanhNghiep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebsiteKLTN.doanhnghiep')),
            ],
        ),
        migrations.CreateModel(
            name='DonHangMomentary',
            fields=[
                ('MaDonHang', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('IDDoiTac', models.CharField(default='NONE', max_length=60)),
                ('LoaiHangHoa', models.CharField(default='NONE', max_length=60)),
                ('TrongTai', models.CharField(default='NONE', max_length=60)),
                ('DiaDiemNhanHang', models.CharField(default='NONE', max_length=300)),
                ('NgayNhanHang', models.DateField(blank=True, default=datetime.date.today)),
                ('GioNhanHang', models.TimeField(blank=True)),
                ('DiaDiemGiaoHang', models.CharField(default='NONE', max_length=300)),
                ('NgayGiaoHang', models.DateField(blank=True, default=datetime.date.today)),
                ('GioGiaoHang', models.TimeField(blank=True)),
                ('ChuY', models.CharField(default='NONE', max_length=60)),
                ('TrangThai', models.CharField(default='Chưa Giao', max_length=60)),
                ('TrangThaiChiTiet', models.CharField(default='Nhận đơn', max_length=60)),
                ('IDKhachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebsiteKLTN.doanhnghiep')),
            ],
            options={
                'get_latest_by': ['MaDonHang'],
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('MaDonHang', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('IDDoiTac', models.CharField(default='NONE', max_length=60)),
                ('LoaiHangHoa', models.CharField(default='NONE', max_length=60)),
                ('TrongTai', models.CharField(default='NONE', max_length=60)),
                ('DiaDiemNhanHang', models.CharField(default='NONE', max_length=300)),
                ('NgayNhanHang', models.DateField(blank=True, default=datetime.date.today)),
                ('GioNhanHang', models.TimeField(blank=True)),
                ('DiaDiemGiaoHang', models.CharField(default='NONE', max_length=300)),
                ('NgayGiaoHang', models.DateField(blank=True, default=datetime.date.today)),
                ('GioGiaoHang', models.TimeField(blank=True)),
                ('ChuY', models.CharField(default='NONE', max_length=60)),
                ('TrangThai', models.CharField(default='Chưa Giao', max_length=60)),
                ('TrangThaiChiTiet', models.CharField(default='Nhận đơn', max_length=60)),
                ('IDKhachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebsiteKLTN.doanhnghiep')),
            ],
            options={
                'get_latest_by': ['MaDonHang'],
            },
        ),
        migrations.CreateModel(
            name='DoiTac_TuNhan',
            fields=[
                ('MaDoiTac_TuNhan', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('MaDoiTac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebsiteKLTN.doitac')),
                ('MaTuNhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebsiteKLTN.tunhan')),
            ],
        ),
        migrations.CreateModel(
            name='DoiTac_DoanhNghiep',
            fields=[
                ('MaDoiTac_DoanhNghiep', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('MaDoanhNghiep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebsiteKLTN.doanhnghiep')),
                ('MaDoiTac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebsiteKLTN.doitac')),
            ],
        ),
    ]
